# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58a5bc3312db9a1105b4bc0887b92180ca5993b920a96530117daf7cc41f3002341f3706e61539b31f394edcd4a253ef335887d32001d9aba3623101d174de77

test:
  secret_key_base: ccbfe831516537eb5d205e04b022d6a1882ecd21cd08150b9172fb0bfd04978361b82a87ed3188d36c63c860bbe22d285845f819e9e9c81cd9c64ab3e40194f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
